### ISSUE TITLE
Still can't access the jupyter instance run on an EC2

### ISSUE THREAD

**Issue by xinkwang** [gw0/docker-keras-full#1]
The CMD I used:
docker run -it --name test_keras_full -d $(ls /dev/nvidia* | xargs -I{} echo '--device={}') -p=6006:6006 -p8888:8888 -v=/home/ubuntu/tensorflow:/home/tensorflow gw000/keras-full

It prints out:
d78258f0af2c1f473ac26c10ad1fe27ed7b2c80b28bf381a2492d8110b4f3563

The errors of accessing the 8888 port:
ERR_CONNECTION_TIMED_OUT

**Comment by gw0** [comment]
Did you managed to solve it?

It printed out the Docker container ID, because you specified `-d` (the same you see in `docker ps`, you can see its log with `docker logs -f ID`). Otherwise the `-it` and `-d` parameters are usually not used simultaneously. Were you connecting to the right IP? Do you have a firewall? What about a local connection from the host to the container port 8888 (`docker inspect test_keras_full` to get the local IP, then `nc -v IP 8888` to connect)?

**Comment by xinkwang** [comment]
It turned out to be a problem caused by my company's security setting. I was able to bypass it and access both jupyter and tensorboard. But I am having trouble with running with GPUs. Is there any additional setting to get it work?


Xin


________________________________

**Comment by gw0** [comment]
Ok.

Getting GPUs to work is error-prone, because Nvidia is changing versions of their proprietary software all the time and different versions are not compatible with each other. I would suggest you check out instructions on https://github.com/gw0/docker-debian-cuda (GPU support is based on that). Especially check the versions of Nvidia kernel driver and CUDA library. You can begin debugging by running `bash` inside the *gw000/keras-full* container:

```
$ docker run -it --rm $(ls /dev/nvidia* | xargs -I{} echo '--device={}') gw000/keras-full bash
```
